version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.24
    - 14.14.25
    - 14.14.26
    - 14.14.28
    - 14.14.30
    - 14.14.32
    - 14.14.33
    - 14.14.34
    - 14.14.37
  - dependency-name: vsce
    versions:
    - 1.84.0
    - 1.85.1
    - 1.86.0
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
