pull_request_rules:
  - name: dependabot
    conditions:
      - and:
        - -draft
        - base=master
        - -closed
        - -conflict
        - label=dependencies
        - author=dependabot[bot]
    actions:
      merge:
        method: merge
